language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# whitelist
branches:
  only:
    - sirisha_travisCI
    - Algorithms-Visualizer-dev
    - master
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - echo "Running Sirisha's tests
         1. insertionSort
         2. oddevenSort
         3. pancakeSort
         4. pigeonholeSort
         5. mergeSort
         6. Quick Sort L-R"
  - pyb -P unittest_module_glob=insertionSort_tests.py
  - pyb
  



 
 
 
 
 